name: weather_app
description: "Weather application using Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-170.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: any
flutter:
  uses-material-design: true